### ISSUE TITLE
ERROR importing java awt

### ISSUE THREAD

**Issue by sunil-singh-chaudhary** [Hansanshi/pptutil#1]
I am trying to add this file in my app but finding error 

import java.awt.geom.Rectangle2D;
import java.awt.image.BufferedImage;

how to importing these two file pls help me here

**Comment by Hansanshi** [comment]
@sunil-singh-chaudhary Hi, sorry to be so late, but I receive no notification from github while I use this website everyday.

You mentioned "app", so I guess you want to use this on Android.

But jvm provided by Android is not standard, so I suggest you to try other ways to solve this problem.
I do find some solutions to support awt on Android, you can google it and try.
